<?php

namespace App\Repository;

/**
 * PoizBasketProductsRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketProductsRepo extends \Doctrine\ORM\EntityRepository
{
}
