<?php

namespace App\Repository;

/**
 * PoizBasketAttributesRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketAttributesRepo extends \Doctrine\ORM\EntityRepository
{
}
