<?php

namespace App\Repository;

/**
 * PoizBasketCategoriesRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketCategoriesRepo extends \Doctrine\ORM\EntityRepository
{
}
