<?php

namespace App\Repository;

/**
 * PoizBasketManufacturersRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketManufacturersRepo extends \Doctrine\ORM\EntityRepository
{
}
