<?php

namespace App\Repository;

/**
 * PoizBasketImagesRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketImagesRepo extends \Doctrine\ORM\EntityRepository
{
}
