<?php

namespace App\Repository;

/**
 * PoizBasketPricesRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoizBasketPricesRepo extends \Doctrine\ORM\EntityRepository
{
}
